name: Deploy

on:
  push:
    branches: [ web ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Steps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
        with:
          version: 15.x

      # Cache NPM
      - name: Cache NPM
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      # Cache Composer
      - name: Cache Composer
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      # Cache Fontello
      - name: Cache Fontello
        id: fontello-cache
        uses: actions/cache@v2
        with:
          path: dist/assets/fontello
          key: fontello-${{ hashFiles('src/icons.json') }}

      # NPM Install
      - name: NPM Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      # Composer Install
      - name: Composer Install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install

      # Fontello
      - name: Download Fontello
        if: steps.fontello-cache.outputs.cache-hit != 'true'
        run: npm run fontello

      # Webpack
      - name: Run Webpack
        run: npm run build

      # Deploy
      - name: Deploy
        env:
          # TODO: Default to repo name instead of "sleek"
          src: './'
          dest: 'sleek@sleek.ssh.wpengine.net:/sites/sleek/wp-content/themes/sleek/'
        # TODO: Clear wpengine cache after rsync (ssh ... wp flush cache?)
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' --exclude-from='./.prodignore' ${{env.src}} ${{env.dest}}
