name: Deploy

on:
  push:
    branches: [ web ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
        with:
          version: 15.x

      - name: Cache NPM
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-${{ hashFiles('package-lock.json') }}

      - name: Cache Composer
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: NPM Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Composer Install
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install

      - name: Build
        run: |
          npm run fontello
          npm run build

      - name: Deploy
        env:
          src: './'
          dest: 'sleek@sleek.ssh.wpengine.net:/sites/sleek/wp-content/themes/sleek/'
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' --exclude-from='./.prodignore' ${{env.src}} ${{env.dest}}
